name: Build DevContainer
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - '.devcontainer/**'
  schedule:
    - cron: '0 0 1 * *'
jobs:
  build-devcontainer:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR }}

      - name: Set image tag
        id: set_tag
        run: |
          if [ "${GITHUB_REF##*/}" = "main" ]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
          else
            # Sanitize branch name: replace / and other non-alphanum with -
            sanitized=$(echo "${GITHUB_REF##*/}" | tr -c 'a-zA-Z0-9_' '-')
            echo "tag=${sanitized}" >> $GITHUB_OUTPUT
          fi

      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/karstenb/hermitgrab-devcontainer
          cacheFrom: ghcr.io/karstenb/hermitgrab-devcontainer
          push: always
          configFile: .devcontainer/build/devcontainer.json
          platform: linux/amd64,linux/arm64
          imageTag: ${{ steps.set_tag.outputs.tag }}