name: Build DevContainer
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - '.devcontainer/**'
jobs:
  build-devcontainer:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/karstenb/hermitgrab-devcontainer
          cacheFrom: ghcr.io/karstenb/hermitgrab-devcontainer
          push: always
          configFile: .devcontainer/build/devcontainer.json